# Generated by Django 6.0 on 2025-12-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
